/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package healthapp;

import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author chris
 */
public class IntroGUI extends javax.swing.JFrame {
    public ArrayList<User> userList;//arrayList to store Login Details

    /**
     * Creates new form Intro
     */
    public IntroGUI() {
        initComponents(); 
        userList = new ArrayList<>();
        readUsers();//puts the users information into the arrayList on load
        //getContentPane().setBackground(new java.awt.Color(57, 214, 18));
        setSize(1000, 596);
        //removes blue background on click from buttons
        //source https://stackoverflow.com/questions/19663009/overriding-button-background
        loginBtn.setContentAreaFilled(false);
        exitBtn.setContentAreaFilled(false);
        createBtn.setContentAreaFilled(false);
        mLoginRb.setContentAreaFilled(false);
        pLoginRb.setContentAreaFilled(false);

    }
    
    
    
    
    //create a file to store the loginDetails and then place them into the userList when called
    private void readUsers(){
        //declare objects
        File f;
        FileInputStream fStream;
        ObjectInputStream oStream;
        
        try{
            //create objects
            f = new File("users.dat");
            fStream = new FileInputStream(f);
            oStream = new ObjectInputStream(fStream);
            
            //use objects
            userList = (ArrayList<User>)oStream.readObject();
            
            oStream.close();
        }
        catch(IOException|ClassNotFoundException e){
            System.out.println("Error: "+e);
        }
    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbBGroup = new javax.swing.ButtonGroup();
        titleLbl = new javax.swing.JLabel();
        messageLbl = new javax.swing.JLabel();
        createBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        loginBtn = new javax.swing.JButton();
        idLbl = new javax.swing.JLabel();
        passwordLbl = new javax.swing.JLabel();
        idTf = new javax.swing.JTextField();
        mLoginRb = new javax.swing.JRadioButton();
        pLoginRb = new javax.swing.JRadioButton();
        messageLbl1 = new javax.swing.JLabel();
        passwordPField = new javax.swing.JPasswordField();
        backgroundLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(996, 559));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleLbl.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        titleLbl.setForeground(new java.awt.Color(124, 95, 53));
        titleLbl.setText("Health Improvement 101");
        getContentPane().add(titleLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, -1, -1));

        messageLbl.setFont(new java.awt.Font("Segoe UI Variable", 3, 14)); // NOI18N
        messageLbl.setForeground(new java.awt.Color(144, 154, 101));
        messageLbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        messageLbl.setText("To use this program, you have to first register an account and then log in with those same details to either Mental or Physical");
        getContentPane().add(messageLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 510, 940, 40));

        createBtn.setBackground(new java.awt.Color(210, 211, 215));
        createBtn.setFont(new java.awt.Font("Segoe UI Variable", 1, 24)); // NOI18N
        createBtn.setText("Register");
        createBtn.setBorder(null);
        createBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createBtn.setFocusable(false);
        createBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBtnActionPerformed(evt);
            }
        });
        getContentPane().add(createBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 100, -1));

        exitBtn.setBackground(new java.awt.Color(208, 209, 213));
        exitBtn.setFont(new java.awt.Font("Segoe UI Variable", 1, 24)); // NOI18N
        exitBtn.setText("Exit");
        exitBtn.setBorder(null);
        exitBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitBtn.setFocusable(false);
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });
        getContentPane().add(exitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 440, 40, -1));

        loginBtn.setBackground(new java.awt.Color(226, 226, 226));
        loginBtn.setFont(new java.awt.Font("Segoe UI Variable", 1, 24)); // NOI18N
        loginBtn.setText("Login");
        loginBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        loginBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginBtn.setFocusPainted(false);
        loginBtn.setFocusable(false);
        loginBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                loginBtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                loginBtnMouseReleased(evt);
            }
        });
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });
        getContentPane().add(loginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 440, 70, -1));

        idLbl.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        idLbl.setText("ID:");
        getContentPane().add(idLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, -1, -1));

        passwordLbl.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        passwordLbl.setText("Password:");
        getContentPane().add(passwordLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 357, -1, -1));

        idTf.setFont(new java.awt.Font("Segoe UI Variable", 0, 18)); // NOI18N
        idTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTfActionPerformed(evt);
            }
        });
        getContentPane().add(idTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 310, 145, -1));

        mLoginRb.setBackground(new java.awt.Color(225, 225, 225));
        rbBGroup.add(mLoginRb);
        mLoginRb.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mLoginRb.setText("Mental Login");
        mLoginRb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(mLoginRb, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 400, -1, -1));

        pLoginRb.setBackground(new java.awt.Color(225, 225, 225));
        rbBGroup.add(pLoginRb);
        pLoginRb.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pLoginRb.setText("Physical Login");
        pLoginRb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pLoginRb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pLoginRbActionPerformed(evt);
            }
        });
        getContentPane().add(pLoginRb, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 400, -1, -1));

        messageLbl1.setFont(new java.awt.Font("Segoe UI Variable", 3, 14)); // NOI18N
        messageLbl1.setForeground(new java.awt.Color(144, 154, 101));
        messageLbl1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        messageLbl1.setText("We aim to improve the overall health of anyone who uses this by providing a variety of options for either their mental or physical wellbeing");
        getContentPane().add(messageLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 940, 40));

        passwordPField.setFont(new java.awt.Font("Segoe UI Variable", 0, 18)); // NOI18N
        getContentPane().add(passwordPField, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 350, 145, -1));

        backgroundLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IntroGUI Images/pexels-totalshape-2383010 (1).jpg"))); // NOI18N
        getContentPane().add(backgroundLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBtnActionPerformed
        // TODO add your handling code here:
        UserGUI myGUI = new UserGUI();
        myGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_createBtnActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_exitBtnActionPerformed

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // TODO add your handling code here:
        
        //source https://stackoverflow.com/questions/53983811/java-passing-arraylist-to-another-jframe
        //source 2 https://stackoverflow.com/questions/60320923/how-do-i-set-a-boolean-inside-a-for-loop-to-true-if-a-value-is-reached
            boolean flag = false; //boolean to check if login is true or not
            for(User u: userList){ //for each object in U,search each of them
                //if the ID or password from the User equals their login details, send them to Mental
                if(u.getId().equals(idTf.getText()) && u.getPassword().equals(passwordPField.getText()) && mLoginRb.isSelected()){ 
                    MentalGUI m = new MentalGUI();
                    m.setVisible(true);
                    this.dispose();
                    flag = true;
                    break;
                    
                }
                //if the ID or password from the User equals their login details, send them to Physical
                else if(u.getId().equals(idTf.getText()) && u.getPassword().equals(passwordPField.getText()) && pLoginRb.isSelected()){
                    PhysicalGUI p = new PhysicalGUI();
                    p.setVisible(true);
                    this.dispose();
                    flag = true;
                    break;
                    
                }
            }
                //if the ID or password from the User does NOT equals their login details / boolean flag is false, run this statement
                if(flag == false){
                //if no parameter is selected or the details are wrong, send an error message
                    if(!pLoginRb.isSelected() && !mLoginRb.isSelected()){
                        JOptionPane.showMessageDialog(null, "Please accept a parameter before you log in");
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "Incorrect login details, please try again");
                    }
                }
            
             
    }//GEN-LAST:event_loginBtnActionPerformed

    private void idTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTfActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_idTfActionPerformed

    private void pLoginRbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pLoginRbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pLoginRbActionPerformed

    private void loginBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtnMouseReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_loginBtnMouseReleased

    private void loginBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtnMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginBtnMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IntroGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IntroGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IntroGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IntroGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IntroGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundLbl;
    private javax.swing.JButton createBtn;
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel idLbl;
    public javax.swing.JTextField idTf;
    private javax.swing.JButton loginBtn;
    private javax.swing.JRadioButton mLoginRb;
    private javax.swing.JLabel messageLbl;
    private javax.swing.JLabel messageLbl1;
    private javax.swing.JRadioButton pLoginRb;
    private javax.swing.JLabel passwordLbl;
    private javax.swing.JPasswordField passwordPField;
    private javax.swing.ButtonGroup rbBGroup;
    private javax.swing.JLabel titleLbl;
    // End of variables declaration//GEN-END:variables
}
