/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package healthapp;

/**
 *
 * @author flips
 */
public class MentalDietGUI extends javax.swing.JFrame {

    /**
     * Creates new form MentalDietGUI
     */
    public MentalDietGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mDietMenuLbl = new javax.swing.JLabel();
        mDietLbl = new javax.swing.JLabel();
        mDietTf = new javax.swing.JTextField();
        mDietTypeBtn = new javax.swing.JButton();
        mentalMenuBtn = new javax.swing.JButton();
        mCaloriesLbl = new javax.swing.JLabel();
        mCaloriesTf = new javax.swing.JTextField();
        saveMDietBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mDietMenuLbl.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        mDietMenuLbl.setText("Mental Wellbeing Diet");

        mDietLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        mDietLbl.setText("Diet Type:");

        mDietTf.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        mDietTypeBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        mDietTypeBtn.setText("Types of Diet");
        mDietTypeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mDietTypeBtnActionPerformed(evt);
            }
        });

        mentalMenuBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        mentalMenuBtn.setText("Back to Mental Menu");
        mentalMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mentalMenuBtnActionPerformed(evt);
            }
        });

        mCaloriesLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        mCaloriesLbl.setText("Calories:");

        mCaloriesTf.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        saveMDietBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        saveMDietBtn.setText("Save");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(mentalMenuBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
                .addComponent(mDietTypeBtn)
                .addGap(19, 19, 19))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(mDietLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mDietTf, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(mCaloriesLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mCaloriesTf, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(mDietMenuLbl))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(saveMDietBtn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mDietMenuLbl)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mDietLbl)
                    .addComponent(mDietTf, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mCaloriesLbl)
                    .addComponent(mCaloriesTf, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(saveMDietBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mDietTypeBtn)
                    .addComponent(mentalMenuBtn))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mDietTypeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mDietTypeBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mDietTypeBtnActionPerformed

    private void mentalMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mentalMenuBtnActionPerformed
        // TODO add your handling code here:
        MentalGUI mg = new MentalGUI();
        mg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mentalMenuBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MentalDietGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MentalDietGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MentalDietGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MentalDietGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MentalDietGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel mCaloriesLbl;
    private javax.swing.JTextField mCaloriesTf;
    private javax.swing.JLabel mDietLbl;
    private javax.swing.JLabel mDietMenuLbl;
    private javax.swing.JTextField mDietTf;
    private javax.swing.JButton mDietTypeBtn;
    private javax.swing.JButton mentalMenuBtn;
    private javax.swing.JButton saveMDietBtn;
    // End of variables declaration//GEN-END:variables
}
