/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package healthapp;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author flips
 */
public class MentalGUI extends javax.swing.JFrame {
    private ArrayList<Mental> mental;


    /**
     * Creates new form MentalGUI
     */
    public MentalGUI() {
        initComponents();
         mental = new ArrayList<>();
         read();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mentalLbl = new javax.swing.JLabel();
        stressLbl = new javax.swing.JLabel();
        stressLblTf = new javax.swing.JTextField();
        dietBtn = new javax.swing.JButton();
        menuMentalBtn = new javax.swing.JButton();
        displayStressBtn = new javax.swing.JButton();
        removeStressBtn = new javax.swing.JButton();
        saveStressBtn = new javax.swing.JButton();
        sleepHrsLbl = new javax.swing.JLabel();
        sleepHrsTf = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        caloriesLbl = new javax.swing.JLabel();
        caloriesLbl1 = new javax.swing.JLabel();
        caloriesLbl2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mentalLbl.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        mentalLbl.setText("Mental Wellbeing");

        stressLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        stressLbl.setText("Stress Level: ");

        stressLblTf.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        stressLblTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stressLblTfActionPerformed(evt);
            }
        });

        dietBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        dietBtn.setText("Search");
        dietBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dietBtnActionPerformed(evt);
            }
        });

        menuMentalBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        menuMentalBtn.setText("Menu");
        menuMentalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMentalBtnActionPerformed(evt);
            }
        });

        displayStressBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        displayStressBtn.setText("Display");
        displayStressBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayStressBtnActionPerformed(evt);
            }
        });

        removeStressBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        removeStressBtn.setText("Remove");
        removeStressBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeStressBtnActionPerformed(evt);
            }
        });

        saveStressBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        saveStressBtn.setText("Save");
        saveStressBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveStressBtnActionPerformed(evt);
            }
        });

        sleepHrsLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        sleepHrsLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sleepHrsLbl.setText("Sleep Hours:");

        sleepHrsTf.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sleepHrsTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sleepHrsTfActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Id");

        caloriesLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        caloriesLbl.setText("Calories:");

        caloriesLbl1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        caloriesLbl1.setText("Calories:");

        caloriesLbl2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        caloriesLbl2.setText("Calories:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(sleepHrsLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(sleepHrsTf, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(stressLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(stressLblTf, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(mentalLbl))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(caloriesLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(159, 159, 159))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(caloriesLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(caloriesLbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(saveStressBtn)
                        .addGap(18, 18, 18)
                        .addComponent(displayStressBtn)
                        .addGap(18, 18, 18)
                        .addComponent(removeStressBtn)
                        .addGap(18, 18, 18)
                        .addComponent(dietBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(menuMentalBtn)))
                .addContainerGap(170, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(mentalLbl)
                        .addGap(79, 79, 79))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(caloriesLbl)
                        .addGap(18, 18, 18)))
                .addComponent(caloriesLbl1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(caloriesLbl2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stressLbl, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(stressLblTf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sleepHrsLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sleepHrsTf, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveStressBtn)
                    .addComponent(displayStressBtn)
                    .addComponent(removeStressBtn)
                    .addComponent(dietBtn)
                    .addComponent(menuMentalBtn))
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuMentalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMentalBtnActionPerformed
        // TODO add your handling code here:
        UserGUI mg = new UserGUI();
        mg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuMentalBtnActionPerformed

    private void dietBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dietBtnActionPerformed
        // TODO add your handling code here:
        MentalDietGUI mdg = new MentalDietGUI();
        mdg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_dietBtnActionPerformed

    private void stressLblTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stressLblTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stressLblTfActionPerformed

    private void saveStressBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveStressBtnActionPerformed
        // TODO add your handling code here:
       
        
    }//GEN-LAST:event_saveStressBtnActionPerformed

    private void sleepHrsTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sleepHrsTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sleepHrsTfActionPerformed

    private void displayStressBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayStressBtnActionPerformed
        // TODO add your handling code here:
        
            if(mental.isEmpty()){
            JOptionPane.showMessageDialog(null,"Sorry, there are no details added in the system");
        }
        else{
            //traversing an ArrayList
            for(int i = 0; i < mental.size();i++){
                JOptionPane.showMessageDialog(null,mental.get(i).getDetails());
            }
        }
     
    }//GEN-LAST:event_displayStressBtnActionPerformed

    private void removeStressBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeStressBtnActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_removeStressBtnActionPerformed

     private void clearUserFields(){ //clears the textfields
        stressLblTf.setText(" ");
        sleepHrsTf.setText(" ");
     
    }
    
    
     private void save(){ //saves the user information into the file
        //declare objects
        File f;
        FileOutputStream fStream;
        ObjectOutputStream oStream;
        
        try{
            //create objects
            f = new File("users.dat");
            fStream = new FileOutputStream(f);
            oStream = new ObjectOutputStream(fStream);
            
            //use objects
            oStream.writeObject(mental);
        }
        catch(IOException e){
            System.out.println("Error:"+e);
        }
    }
    private void read(){
        //declare objects
        File f;
        FileInputStream fStream;
        ObjectInputStream oStream;
        
        try{
            //create objects
            f = new File("user.dat");
            fStream = new FileInputStream(f);
            oStream = new ObjectInputStream(fStream);
            
            //use objects
            mental = (ArrayList<Mental>)oStream.readObject();
            
            oStream.close();
        }
        catch(IOException|ClassNotFoundException e){
            System.out.println("Error:"+e);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MentalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MentalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MentalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MentalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MentalGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel caloriesLbl;
    private javax.swing.JLabel caloriesLbl1;
    private javax.swing.JLabel caloriesLbl2;
    private javax.swing.JButton dietBtn;
    private javax.swing.JButton displayStressBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel mentalLbl;
    private javax.swing.JButton menuMentalBtn;
    private javax.swing.JButton removeStressBtn;
    private javax.swing.JButton saveStressBtn;
    private javax.swing.JLabel sleepHrsLbl;
    private javax.swing.JTextField sleepHrsTf;
    private javax.swing.JLabel stressLbl;
    private javax.swing.JTextField stressLblTf;
    // End of variables declaration//GEN-END:variables
}
