/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package healthapp;

/**
 *
 * @author flips
 */
public class PhysicalCardioGUI extends javax.swing.JFrame {

    /**
     * Creates new form PhysicalActivityGUI
     */
    public PhysicalCardioGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pCardioLbl = new javax.swing.JLabel();
        pCardioTypeLbl = new javax.swing.JLabel();
        pCardioTypeTf = new javax.swing.JTextField();
        pCardioDurationLbl = new javax.swing.JLabel();
        pCardioDurationTf = new javax.swing.JTextField();
        pActivitySaveBtn = new javax.swing.JButton();
        physicalMenuBtn = new javax.swing.JButton();
        pCardioTypeBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pCardioLbl.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        pCardioLbl.setText("Physical Wellbeing Cardio");

        pCardioTypeLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        pCardioTypeLbl.setText("Type of Cardio:");

        pCardioTypeTf.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        pCardioDurationLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        pCardioDurationLbl.setText("Cardio Duration:");

        pCardioDurationTf.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        pActivitySaveBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pActivitySaveBtn.setText("Save");

        physicalMenuBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        physicalMenuBtn.setText("Back to Physical Menu");
        physicalMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                physicalMenuBtnActionPerformed(evt);
            }
        });

        pCardioTypeBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        pCardioTypeBtn.setText("Types of Cardio");
        pCardioTypeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pCardioTypeBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pCardioDurationLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pCardioDurationTf, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(pActivitySaveBtn)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pCardioTypeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pCardioLbl)
                                    .addComponent(pCardioTypeTf, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(physicalMenuBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addComponent(pCardioTypeBtn)
                        .addGap(25, 25, 25))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pCardioLbl)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pCardioTypeLbl)
                    .addComponent(pCardioTypeTf, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pCardioDurationLbl)
                    .addComponent(pCardioDurationTf, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(pActivitySaveBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(physicalMenuBtn)
                    .addComponent(pCardioTypeBtn))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void physicalMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_physicalMenuBtnActionPerformed
        // TODO add your handling code here:
        PhysicalGUI pg = new PhysicalGUI();
        pg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_physicalMenuBtnActionPerformed

    private void pCardioTypeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pCardioTypeBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pCardioTypeBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PhysicalCardioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PhysicalCardioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PhysicalCardioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PhysicalCardioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PhysicalCardioGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton pActivitySaveBtn;
    private javax.swing.JLabel pCardioDurationLbl;
    private javax.swing.JTextField pCardioDurationTf;
    private javax.swing.JLabel pCardioLbl;
    private javax.swing.JButton pCardioTypeBtn;
    private javax.swing.JLabel pCardioTypeLbl;
    private javax.swing.JTextField pCardioTypeTf;
    private javax.swing.JButton physicalMenuBtn;
    // End of variables declaration//GEN-END:variables
}
